BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"id"	INTEGER NOT NULL UNIQUE,
	"USERNAME"	TEXT NOT NULL UNIQUE,
	"PASSWORD_HASH"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Client" (
	"id"	INTEGER NOT NULL UNIQUE,
	"USER_ID"	INTEGER NOT NULL UNIQUE,
	"PREFIX"	TEXT,
	"FIRST_NAME"	TEXT NOT NULL,
	"LAST_NAME"	TEXT NOT NULL,
	"ADDRESS_LINE_1"	TEXT NOT NULL,
	"ADDRESS_LINE_2"	TEXT,
	"CITY"	TEXT NOT NULL,
	"STATE"	TEXT NOT NULL,
	"POST_CODE"	TEXT NOT NULL,
	"NOTES"	TEXT,
	FOREIGN KEY("USER_ID") REFERENCES "User"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ClientContact" (
	"CLIENT_ID"	INTEGER NOT NULL,
	"METHOD"	TEXT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"CONTACT"	TEXT NOT NULL,
	"PREFERRED"	INTEGER NOT NULL,
	PRIMARY KEY("CLIENT_ID","METHOD")
);
CREATE TABLE IF NOT EXISTS "Pet" (
	"id"	INTEGER NOT NULL UNIQUE,
	"CLIENT_ID"	INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL,
	"TYPE"	TEXT NOT NULL,
	"GENDER"	TEXT NOT NULL,
	"NEUTERED"	INTEGER NOT NULL,
	"WEIGHT_KG"	INTEGER NOT NULL,
	"COAT_COLOR"	TEXT NOT NULL,
	"BIRTHDAY"	INTEGER NOT NULL,
	"ALLERGY_NOTE"	TEXT,
	"NOTE"	TEXT,
	"VACCINATION"	TEXT NOT NULL,
	"VACCINATION_DATE"	INTEGER NOT NULL,
	"VACCINATION_NEXT"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
