CREATE TABLE IF NOT EXISTS "user" (
	"USER_ID"	TEXT NOT NULL UNIQUE,
	"CUSTOMER_ID"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("USER_ID")
);
CREATE TABLE IF NOT EXISTS "Pet" (
	"id"	INTEGER NOT NULL UNIQUE,
	"CLIENT_ID"	INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL,
	"TYPE"	TEXT NOT NULL,
	"GENDER"	TEXT NOT NULL,
	"NEUTERED"	INTEGER NOT NULL,
	"WEIGHT_KG"	INTEGER NOT NULL,
	"COAT_COLOR"	TEXT NOT NULL,
	"BIRTHDAY"	INTEGER NOT NULL,
	"ALLERGY_NOTE"	TEXT,
	"NOTE"	TEXT,
	"VACCINATION"	TEXT NOT NULL,
	"VACCINATION_DATE"	INTEGER NOT NULL,
	"VACCINATION_NEXT"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
